# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: 8083

spring:
  # JPA settings.
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    show-sql: false

  # H2
  # http://localhost:8083/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console

  # Datasource
  datasource:
    url: jdbc:h2:file:~/gamestore;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
